PREFIX xapi: <http://semweb.mmlab.be/ns/tincan2prov/> 
PREFIX prov: <http://www.w3.org/ns/prov#>

CONSTRUCT {
    ?statement a ?type .
    ?statement a prov:Bundle .
    ?actor a prov:Agent .
    ?statement prov:WasGeneratedBy [ a prov:Activity]
}
WHERE { 
    ?statement a xapi:Statement .
    ?statement a ?type .
    ?statement xapi:actor ?actor .
}
